import requests
# Unofficial API library for Google Trends
from pytrends.request import TrendReq
# Import the GenerativeModel class
import google.generativeai as genai
import os
import pathlib
import textwrap
from IPython.display import display
from IPython.display import Markdown

def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))


# function returns an array with the top ten trending items
def top_ten_list():
   # Create a pytrends request object
    pytrends = TrendReq(hl='en-US', tz=360)  # hl sets the language, tz sets the timezone offset (in minutes)

    # Fetch the trending searches
    trending_searches = pytrends.trending_searches(pn='united_states')
    # place into an array
    trends_array = []
    for row in trending_searches.head(10).itertuples(index=False):
       trends_array.append(row[0])

    return trends_array

# Return a string generated by AI to be used a paragraph
# takes in a string keyyword
def generate_paragraph(trend):
    # Get user input for the prompt
    prompt = f"Why is {trend} trending right now? Give a short 2 sentence explanation."

    GOOGLE_API_KEY= "AIzaSyCX_EyC2Rf9hzNQrkqdslC0skEMgB9dIPQ"
    genai.configure(api_key=GOOGLE_API_KEY)

    # Initialize the model
    model = genai.GenerativeModel('gemini-pro')

    # Generate text content
    response = model.generate_content(prompt)

    return response.text
